[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "python3 -m uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
